/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnnoncesRouteImport } from './routes/annonces'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PublierRouteImport } from './routes/publier'
import { Route as AnnonceSlugRouteImport } from './routes/annonce.$slug'
import { Route as AnnoncesIndexRouteImport } from './routes/annonces.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as PageSlugRouteImport } from './routes/page.$slug'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesRoute = AnnoncesRouteImport.update({
  id: '/annonces',
  path: '/annonces',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PublierRoute = PublierRouteImport.update({
  id: '/publier',
  path: '/publier',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnonceSlugRoute = AnnonceSlugRouteImport.update({
  id: '/annonce/$slug',
  path: '/annonce/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesIndexRoute = AnnoncesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnnoncesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const PageSlugRoute = PageSlugRouteImport.update({
  id: '/page/$slug',
  path: '/page/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/annonces': typeof AnnoncesRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/favoris': typeof FavorisRoute
  '/messages': typeof MessagesRoute
  '/publier': typeof PublierRoute
  '/annonce/$slug': typeof AnnonceSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/page/$slug': typeof PageSlugRoute
  '/annonces/': typeof AnnoncesIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/favoris': typeof FavorisRoute
  '/messages': typeof MessagesRoute
  '/publier': typeof PublierRoute
  '/annonce/$slug': typeof AnnonceSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/page/$slug': typeof PageSlugRoute
  '/annonces': typeof AnnoncesIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/annonces': typeof AnnoncesRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/favoris': typeof FavorisRoute
  '/messages': typeof MessagesRoute
  '/publier': typeof PublierRoute
  '/annonce/$slug': typeof AnnonceSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/page/$slug': typeof PageSlugRoute
  '/annonces/': typeof AnnoncesIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/annonces'
    | '/auth'
    | '/blog'
    | '/dashboard'
    | '/faq'
    | '/favoris'
    | '/messages'
    | '/publier'
    | '/annonce/$slug'
    | '/blog/$slug'
    | '/page/$slug'
    | '/annonces/'
    | '/api/public/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/dashboard'
    | '/faq'
    | '/favoris'
    | '/messages'
    | '/publier'
    | '/annonce/$slug'
    | '/blog/$slug'
    | '/page/$slug'
    | '/annonces'
    | '/api/public/health'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/annonces'
    | '/auth'
    | '/blog'
    | '/dashboard'
    | '/faq'
    | '/favoris'
    | '/messages'
    | '/publier'
    | '/annonce/$slug'
    | '/blog/$slug'
    | '/page/$slug'
    | '/annonces/'
    | '/api/public/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnnoncesRoute: typeof AnnoncesRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  FavorisRoute: typeof FavorisRoute
  MessagesRoute: typeof MessagesRoute
  PublierRoute: typeof PublierRoute
  AnnonceSlugRoute: typeof AnnonceSlugRoute
  PageSlugRoute: typeof PageSlugRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces': {
      id: '/annonces'
      path: '/annonces'
      fullPath: '/annonces'
      preLoaderRoute: typeof AnnoncesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publier': {
      id: '/publier'
      path: '/publier'
      fullPath: '/publier'
      preLoaderRoute: typeof PublierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonce/$slug': {
      id: '/annonce/$slug'
      path: '/annonce/$slug'
      fullPath: '/annonce/$slug'
      preLoaderRoute: typeof AnnonceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces/': {
      id: '/annonces/'
      path: '/'
      fullPath: '/annonces/'
      preLoaderRoute: typeof AnnoncesIndexRouteImport
      parentRoute: typeof AnnoncesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/page/$slug': {
      id: '/page/$slug'
      path: '/page/$slug'
      fullPath: '/page/$slug'
      preLoaderRoute: typeof PageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnnoncesRouteChildren {
  AnnoncesIndexRoute: typeof AnnoncesIndexRoute
}

const AnnoncesRouteChildren: AnnoncesRouteChildren = {
  AnnoncesIndexRoute: AnnoncesIndexRoute,
}

const AnnoncesRouteWithChildren = AnnoncesRoute._addFileChildren(
  AnnoncesRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnnoncesRoute: AnnoncesRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  FavorisRoute: FavorisRoute,
  MessagesRoute: MessagesRoute,
  PublierRoute: PublierRoute,
  AnnonceSlugRoute: AnnonceSlugRoute,
  PageSlugRoute: PageSlugRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
